source("C:/Users/rowcliffe.m/Documents/GitHub/CTtracking/CTtracking.r")
setwd("C:/Users/rowcliffe.m/Documents/CameraTrapping/REM/Calibration/Mytool2018/Gee data")

cdat <- read.poledat("camcal.csv", "pole_id;distance;length")
ddat <- data.frame(x=3264, y=2449)
cmod <- cal.cam(cdat, ddat)
plot(cmod)

#ccdat <- rbind(cdat, cdat)
#ccdat$cam_id <- rep(c("a","b"), each=nrow(cdat))
#ddat <- rbind(ddat, ddat)
#ddat$cam_id <- c("a","b")
#ccmod <- cal.cam(ccdat, ddat)
#lapply(ccmod, plot)

setwd("./DigiDat")
pth <- getwd()
merge.csv(pth, sitecol="CTsite")
setwd("./merged")
sdat <- read.poledat("merged.csv", "height")
smod <- cal.site(cmod, sdat)
lapply(smod, plot)
